modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="carnelian"
version="1.8.1"
displayName="Carnelian"
credits="MCreator, BeepBox, Aseprite, RaineTyler"
displayURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
logoFile="logo.png"
authors="Damckell"
description='''
A simple mod that adds such things as rock candy, wands with magical properties, a couple of new color stone variants, and a new gem called Carnelian.
'''

[[dependencies.carnelian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




