modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved"

[[mods]]
modId="carnelian"
version="1.6.1"
displayName="Carnelian"
credits="MCreator, BeepBox, Aseprite, and my friends who told me I could!"
displayURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
logoFile="logo.png"
authors="Damckell"
description='''
A simple mod that adds such things as rock candy, wands with magical properties, a couple of new color stone variants, and a new gem called Carnelian.
'''

[[dependencies.carnelian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




